let mapleader = ","
let g:mapleader = ","
nmap <leader>v :split ~/.vimrc<CR>
au BufRead $MYVIMRC set foldmethod=marker

" Plugins
set nocompatible
set number
set relativenumber

call plug#begin('~/.vim/plugged')

" Editing Mechanics
Plug 'machakann/vim-sandwich'            " More vim-like vim-surround?
Plug 'tpope/vim-dispatch'                " Run background processes in tmux tabs
Plug 'tpope/vim-commentary'              " Toggle comments (gc to comment, gcc to uncomment)
Plug 'Raimondi/delimitMate'              " Automatically insert matching brackets
Plug 'tpope/vim-endwise'                 " Automatically insert end
Plug 'tommcdo/vim-lion'                  " Align comments etc with gl#
Plug 'tpope/vim-speeddating'             " <C-A> and <C-X> for dates
Plug 'icatalina/vim-case-change'         " Makes ~ cycle through camel, snake case
Plug 'AndrewRadev/splitjoin.vim'         " gS -- transform to multiline; gJ -- transform to oneliner
Plug 'hrsh7th/vim-vsnip'                 " Needed to fix <tab> in insert mode

" UI Enhancements
Plug 'rubik/vim-base16-paraiso'
Plug 'arzg/vim-colors-xcode'
Plug 'morhetz/gruvbox'
Plug 'sonph/onehalf', { 'rtp': 'vim' }
Plug 'airblade/vim-gitgutter'            " Diff markers in the gutter
Plug 'bling/vim-airline'                 " Status
Plug 'vim-airline/vim-airline-themes'

" IDE-Like Behavior
Plug 'tpope/vim-fugitive'                " Git
Plug 'tpope/vim-rhubarb'                 " GitHub
Plug 'rizzatti/dash.vim'                 " Open the docs
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'neovim/nvim-lspconfig'
Plug 'ojroques/nvim-lspfuzzy'
Plug 'neovim/nvim-lspconfig'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-path'
Plug 'hrsh7th/cmp-cmdline'
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-vsnip'
Plug 'hrsh7th/vim-vsnip'
Plug 'ntpeters/vim-better-whitespace'    " Highlight trailing whitespace
Plug 'christoomey/vim-tmux-navigator'
if executable('shadowenv')
  Plug 'Shopify/shadowenv.vim'
endif
Plug 'vim-test/vim-test'
Plug 'frazrepo/vim-rainbow'
Plug 'github/copilot.vim'

" Markdown
Plug 'plasticboy/vim-markdown'

" Ruby
Plug 'vim-ruby/vim-ruby'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-bundler'
Plug 'thoughtbot/vim-rspec'
Plug 'noprompt/vim-yardoc'

" YAML
Plug 'stephpy/vim-yaml'
Plug 'pedrohdz/vim-yaml-folds'

" JS and React
Plug 'pangloss/vim-javascript'
Plug 'dense-analysis/ale'
Plug 'peitalin/vim-jsx-typescript'
Plug 'HerringtonDarkholme/yats.vim' " TS syntax highlighter
Plug 'alvan/vim-closetag'
Plug 'lukas-reineke/indent-blankline.nvim'
Plug 'mxw/vim-jsx'
Plug 'othree/yajs.vim'
Plug 'othree/es.next.syntax.vim'
Plug 'Quramy/vim-js-pretty-template'
Plug 'HerringtonDarkholme/yats.vim'

" HTML and CSS
Plug 'mattn/emmet-vim'              " expand abbreviations to html/css
Plug 'hail2u/vim-css3-syntax'
Plug 'gko/vim-coloresque'           " Highlight colors like #009bf9

" GraphQL
Plug 'jparise/vim-graphql'          " graphql syntax highlighter

call plug#end()

let g:ale_fixers = {
 \ '*': ['remove_trailing_lines', 'trim_whitespace'],
 \ 'javascript': ['eslint', 'prettier'],
 \ 'typescript': ['eslint', 'prettier'],
 \ 'typescriptreact': ['eslint', 'prettier'],
 \ 'javascriptreact': ['eslint', 'prettier'],
 \ }

let g:ale_sign_error = '❌'
let g:ale_sign_warning = '⚠️'
let g:ale_fix_on_save = 1
set backspace=eol,start,indent " Let backspace wrap
set whichwrap+=<,>,h,l         " Let movement wrap
set expandtab                  " Use spaces instead of tabs
set smarttab                   " Be smart when using tabs ;)
set shiftwidth=2               " Tab width
set tabstop=2                  " "
set ai                         " Auto indent
set si                         " Smart indent
set wrap                       " Wrap lines
set tw=80                      " Limit line length
set lbr                        " Soft wrap at word boundaries

" Indenting that keeps visuals selected
vnoremap < <gv
vnoremap > >gv

" Fast save
nmap <leader>w :w!<cr>

" Treat long lines as break lines (useful when moving around in them)
map j gj
map k gk

" Don’t open folds when using { and } to move
set foldopen-=block

" Automatically open all folds when opening a file
autocmd BufWinEnter * let &foldlevel = max(map(range(1, line('$')), 'foldlevel(v:val)'))


let delimitMate_expand_cr = 1
let delimitMate_expand_space = 1

let NERDSpaceDelims = 1

map g" <Plug>ReplaceWithCurly


" UI enhancements
syntax enable

set nu           " Show line number
set so=7         " Pad the edge of the screen
set cmdheight=2  " Height of the command bar
set hid          " A buffer becomes hidden when it is abandoned
set showmatch    " Show matching brackets when text indicator is over them
set mat=2        " How many tenths of a second to blink when matching brackets
set laststatus=2 " Always show statusline
set cc=121       " Show where 120 chars is

" GUI Options
if has("gui_running")
 set guifont=IBM\ Plex\ Mono
 set guioptions-=L
 set guioptions-=r
 set showtabline=0
 let g:solarized_menu=0
 let g:airline_powerline_fonts = 0
endif

if has('mouse_sgr')
 set ttymouse=sgr
endif

set termguicolors
colorscheme base16-paraiso
set bg=dark
let g:airline_theme = 'lucius' " 'lucius' is a good general-purpose theme

let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#branch#enabled= 1

" For easy replacement of HTML tags
nmap srt <Plug>(operator-sandwich-replace)<Plug>(textobj-sandwich-query-a)tt

" IDE-like behavior
set ignorecase              " Ignore case when searching
set hlsearch                " Highlight search results
set incsearch               " Search as I type
set smartcase               " When searching try to be smart about cases
set wildmenu                " Turn on the WiLd menu
set wildignore=*.o,*~,*.pyc " Ignore compiled files
set undofile                " Persistent history between sessions

" Toggle spell check
nnoremap <silent> <leader>s :set spell!<CR>
set spelllang=en

" cd to this file’s directory
nnoremap <silent><leader>lcd :cd %:p:h<cr>

" Clean up when <leader><cr> is pressed
map <silent> <leader><cr> :noh<cr>:ccl<cr>:GitGutterAll<cr>

set mouse=a " Mouses are useful

" Smart way to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" Close the current buffer
map <leader>bd :Kwbd<cr>
" Close all the buffers
map <leader>ba :1,1000 bd!<cr>

map <leader>e :Explore<cr>

" Specify the behavior when switching between buffers
try
 set switchbuf=useopen,usetab,newtab
   set stal=2
   catch
   endtry
   " Return to last edit position when opening files
   autocmd BufReadPost *
     \ if line("'\"") > 0 && line("'\"") <= line("$") |
     \   exe "normal! g`\"" |
     \ endif

"Remember info about open buffers on close
set viminfo^=%

" Search for current selection
vnoremap * y/\V<C-r>=escape(@",'/\')<CR><CR>

" Dash
nnoremap <silent> K :Dash<cr>

" LSP
lua << EOF
local nvim_lsp = require('lspconfig')

-- Use an on_attach function to only map the following keys
-- after the language server attaches to the current buffer
local on_attach = function(client, bufnr)
  local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
  local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end

  --Enable completion triggered by <c-x><c-o>
  buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

  -- Mappings.
  local opts = { noremap=true, silent=true }

  -- See `:help vim.lsp.*` for documentation on any of the below functions
  buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
  buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
  buf_set_keymap('n', '<leader><leader>', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
  buf_set_keymap('n', '<leader>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
  buf_set_keymap('n', '<leader>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
  buf_set_keymap('n', '<leader>ca', '<cmd>lua vim.lsp.buf.code_action()<CR>', opts)
  buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
  buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
  buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
  buf_set_keymap('n', '<leader>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)
  buf_set_keymap("n", "<leader>f", "<cmd>lua vim.lsp.buf.formatting()<CR>", opts)

end

-- Shopify's rubocop lsp
local configs = require 'lspconfig.configs'
local util = require 'lspconfig/util'
configs.rubocop = {
  name = "Rubocop",
  default_config = {
    root_dir = util.root_pattern('Gemfile', '.git'),
    cmd = { "bundle", "exec", "rubocop-lsp" },
    filetypes = { "ruby" },
  },
}

-- Use a loop to conveniently call 'setup' on multiple servers and
-- map buffer local keybindings when the language server attaches
local servers = { "sorbet", "rust_analyzer", "rubocop" }
for _, lsp in ipairs(servers) do
  nvim_lsp[lsp].setup {
    on_attach = on_attach,
    flags = {
      debounce_text_changes = 150,
    }
  }
end

require('lspfuzzy').setup {
  methods = 'all',         -- either 'all' or a list of LSP methods (see below)
  jump_one = true,         -- jump immediately if there is only one location
  callback = nil,          -- callback called after jumping to a location
  fzf_preview = {          -- arguments to the FZF '--preview-window' option
    'right:+{2}-/2'          -- preview on the right and centered on entry
  },
  fzf_action = {           -- FZF actions
    ['ctrl-t'] = 'tabedit',  -- go to location in a new tab
    ['ctrl-v'] = 'vsplit',   -- go to location in a vertical split
    ['ctrl-x'] = 'split',    -- go to location in a horizontal split
  },
  fzf_modifier = ':~:.',   -- format FZF entries, see |filename-modifiers|
  fzf_trim = true,         -- trim FZF entries
}

EOF


lua <<EOF
local t = function(str)
  return vim.api.nvim_replace_termcodes(str, true, true, true)
end

local check_back_space = function()
    local col = vim.fn.col('.') - 1
    return col == 0 or vim.fn.getline('.'):sub(col, col):match('%s') ~= nil
end

-- Use (s-)tab to:
--- move to prev/next item in completion menuone
--- jump to prev/next snippet's placeholder
EOF

" Fzf
    " Customize fzf colors to match your color scheme
    " - fzf#wrap translates this to a set of `--color` options
    let g:fzf_colors =
    \ { 'fg':      ['fg', 'Normal'],
      \ 'bg':      ['bg', 'Normal'],
      \ 'hl':      ['fg', 'Comment'],
      \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
      \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
      \ 'hl+':     ['fg', 'Statement'],
      \ 'info':    ['fg', 'PreProc'],
      \ 'border':  ['fg', 'Ignore'],
      \ 'prompt':  ['fg', 'Conditional'],
      \ 'pointer': ['fg', 'Exception'],
      \ 'marker':  ['fg', 'Keyword'],
      \ 'spinner': ['fg', 'Label'],
      \ 'header':  ['fg', 'Comment'] }

command! -bang -nargs=* GGrep
  \ call fzf#vim#grep(
  \   'git grep --line-number -- '.shellescape(<q-args>), 0,
  \   fzf#vim#with_preview({'dir': systemlist('git rev-parse --show-toplevel')[0]}), <bang>0)

command! -bang -nargs=* GGrepNoTests
  \ call fzf#vim#grep(
  \   'git grep --line-number '.shellescape(<q-args>), 0,
  \   { 'dir': systemlist('git rev-parse --show-toplevel')[0] }, <bang>0)

nmap <silent> <c-p> :GFiles<CR>
nmap <silent> <c-t> :Buffers<CR>
nmap <silent> <c-f> :GGrep<CR>

" An action can be a reference to a function that processes selected lines
function! s:build_quickfix_list(lines)
  call setqflist(map(copy(a:lines), '{ "filename": v:val }'))
  copen
  cc
endfunction

let g:fzf_action = {
  \ 'ctrl-q': function('s:build_quickfix_list'),
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }

" Vim Test
nmap <silent> <leader>tn :TestNearest<CR>
nmap <silent> <leader>tf :TestFile<CR>
nmap <silent> <leader>ts :TestSuite<CR>
nmap <silent> <leader>tl :TestLast<CR>
nmap <silent> <leader>tg :TestVisit<CR>
let test#strategy = "dispatch"

" HTML
let g:closetag_filenames = '*.html,*.xhtml,*.jsx,*.tsx'
let g:closetag_xhtml_filenames = '*.xhtml,*.jsx,*.tsx'
let g:closetag_filetypes = 'html,js'
let g:closetag_xhtml_filetype = 'xhtml,jsx,tsx'
let g:closetag_emptyTags_caseSensitive = 1
let g:closetag_regions = {
  \ 'typescript.tsx': 'jsxRegion,tsxRegion',
  \ 'javascript.jsx': 'jsxRegion',
  \ }
let g:closetag_shortcut = '>'
au FileType eruby,html,xhtml let b:delimitMate_matchpairs = "(:),[:],{:}"

" Javascript etc.
let g:jsx_ext_required = 0

au FileType javascript set foldmethod=syntax
au FileType javascript let b:delimitMate_quotes = "\"'`"

" Markdown
let g:vim_markdown_toc_autofit = 1
let g:vim_markdown_folding_level = 6
let g:vim_markdown_frontmatter = 1
let g:vim_markdown_fenced_languages = [
\ 'js=typescript',
\ 'jsx=typescript',
\ 'ts=typescript',
\ 'haskell=haskell',
\ 'tsx=typescript']
au FileType markdown setlocal formatoptions=twacq spell
autocmd FileType markdown call textobj#quote#init()

" Ruby
au FileType ruby setlocal iskeyword-=.

let g:rails_projections = {
\   "config/routes.rb": {
\     "command": "routes"},
\   "spec/features/*_spec.rb": {
\     "type": "feature",
\     "template": [
\       "require 'rails_helper'",
\       "",
\       "feature '{underscore|capitalize|blank}' do",
\       "",
\       "end" ]}}

let g:rails_gem_projections = {
\   "factory_bot_rails": {
\     "spec/factories/*.rb": {
\       "type": "factory",
\       "template": [
\         "FactoryBot.define do",
\         "  factory :{underscore} do",
\         "",
\         "  end",
\         "end"],
\       "related": "app/models/{}.rb" } } }

" Fade out sorbet signatures
augroup format_ruby
  autocmd Syntax ruby syn region sorbetSig start='sig {' end='}'
  autocmd Syntax ruby syn region sorbetSig start='sig do' end='end'
  autocmd Syntax ruby hi def link sorbetSig Comment
augroup END

let g:splitjoin_trailing_comma = 1
let g:splitjoin_ruby_hanging_args = 0
let g:splitjoin_ruby_curly_braces = 0
let g:splitjoin_ruby_options_as_arguments = 1

" Technical details
set encoding=utf8
set ffs=unix,dos,mac " Use Unix as the standard file type
set lazyredraw       " Don't redraw while executing macros (perf)
set magic            " For regular expressions turn magic on
set noerrorbells     " No annoying sound on errors
set tm=500           " Timeout
set history=700      " Long memory
set hidden           " CoC wants this set?
set updatetime=300   " So CursorHold fires after a more reasonable time
