#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

prompt sorin

unsetopt correct

alias x='exit'
alias c='clear'

if command -v gdircolors &> /dev/null; then
  alias dircolors='gdircolors'
fi
eval $(dircolors ~/.LS_COLORS)
alias ls="ls -GF"

alias be='bundle exec'
alias vim='nvim'
alias vi='nvim'

alias pdf='pandoc --to=latex -o out.pdf --latex-engine=xelatex --variable documentclass=amsart --variable mainfont="FreightText Pro" --variable monofont="IBM Plex Mono" --variable fontsize=11'

if command -v batcat &> /dev/null; then
  alias cat='batcat'
elif command -v bat &> /dev/null; then
  alias cat='bat'
fi

# Directory aliases are not common across machines, so source the local file
if [[ -s "${ZDOTDIR:-$HOME}/.zshdirs" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshdirs"
fi

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

autoload -Uz compinit && compinit

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"


[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
