#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

prompt sorin

unsetopt correct

alias x='exit'
alias c='clear'

if command -v gdircolors &> /dev/null; then
  alias dircolors='gdircolors'
fi
eval $(dircolors ~/.LS_COLORS)
alias ls="ls -GF"

alias be='bundle exec'
# alias git='hub'
alias vim='nvim'
alias vi='nvim'
alias s='cd ~/Documents/school/4'

alias pdf='pandoc --to=latex -o out.pdf --latex-engine=xelatex --variable documentclass=amsart --variable mainfont="FreightText Pro" --variable monofont="IBM Plex Mono" --variable fontsize=11'

if command -v batcat &> /dev/null; then
  alias cat='batcat'
elif command -v bat &> /dev/null; then
  alias cat='bat'
fi

# Directory aliases are not common across machines, so source the local file
if [[ -s "${ZDOTDIR:-$HOME}/.zshdirs" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshdirs"
fi

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

autoload -Uz compinit && compinit

export JAVA_14_HOME=$(/usr/libexec/java_home -v14)
alias java14='export JAVA_HOME=$JAVA_14_HOME'

# default to Java 14
java14
export PATH="/opt/homebrew/opt/ruby@3.0/bin:$PATH"
export PATH="/opt/homebrew/opt/ruby@3.0/bin:$PATH"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# bun completions
[ -s "/Users/keithradford/.bun/_bun" ] && source "/Users/keithradford/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/homebrew/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/homebrew/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/opt/homebrew/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/opt/homebrew/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

